### ISSUE TITLE
Typeo and NullPointerException clicking Shodw ordering list button

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#175]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Click Show filters button. 
1. Click Shodw ordering list. 

**Expected results**
* The ordering list will appear. 

**Received results**
* Typeo in button label: "d" is unnecessary. 
* !MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException

![shodw_ordering](https://user-images.githubusercontent.com/16755484/107032283-dbd66580-67b3-11eb-9e7f-12a7936d58ab.jpg)
[showd_ordering_list_log.txt](https://github.com/sed-szeged/iFL4Eclipse/files/5932295/showd_ordering_list_log.txt)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.1

The "Shodw ordering list" button has been removed from the Filters part because it is a separate functionality from filtering. The Sorting dual list view can be opened with the button on the iFL Main part (the one with the cards)

**Comment by brita-sed** [comment]
The button has been removed, so the bug has been fixed.
