### ISSUE TITLE
Opening iFL tab: Source and Refactor menupoints disappear

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#18]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the  C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 

**Expected results**
* iFL tabs appears. Menupoints won't change. 

**Received results**
* Source and Refactor menupoints disappear.
![no_ifl_tab](https://user-images.githubusercontent.com/16755484/54371785-4b03b780-467a-11e9-9558-8c0126faf5c6.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
This rather strange. Could you consistently replicate this phenomenon? Could you please detail each and every click or action you take? Thank you.

**Comment by brita-sed** [comment]
Video from the operation: https://drive.google.com/open?id=1OXLXLJw7LGQpJAtWashuPdaBOQTM212I

**Comment by geryxyz** [comment]
I think this is not a bug. You are able to use source code related action or apply refactoring if there is a source code item selected. Since you start each iFL session by selecting a project which is a source code item these menus are available. When the session started the new panel get the focus hence also change the selection to none which is clearly not a source code item.

Please try the followings 
1 select a project 
2 change the focus by navigate to an other panel, for example Console in the bottom. Without starting any iFL session or activating any iFL menu or button. 
3 these menus should disappear if my assumptions are correct.
