### ISSUE TITLE
Score of "User feedback disabled" elements can be set to 0 with context

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#33]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load score...* button. 
1. Load the appropriate CSV file. 
1. Find an element with context, and where one of the context is "user feedback disabled". 
1. Set "Context (including selected items) seem no suspicios" option from the right-click menu. 

**Expected results**
* Because the context contains "user feedback disabled" element, should it's score set to be 0? 

**Received results**
* All element including “user feedback disabled” get 0 score. 
![context_set_to_zero](https://user-images.githubusercontent.com/16755484/55177227-051f1700-5183-11e9-81a6-f7086b244330.jpg)

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.33.1

**Expected behavior:**

1. If the context of the selected element contains an element that's interactivity is set to "disabled" (non-interactive), a dialog window pops up.
2. The dialog window warns the user that the current feedback contains "non-interactive" elements and that the score of these elements will not be affected by the feedback.
3. The dialog window also offers the possibility for the user to highlight all the elements that belong in the currently selected element's context but will not be affected due to being "non-interactive".
4. Should the user choose the option to highlight these elements, a red background will mark them in the table .

![image](https://user-images.githubusercontent.com/48832842/73169858-537fa800-40fd-11ea-938e-d32323ee8bf0.png)

![image](https://user-images.githubusercontent.com/48832842/73169900-6db98600-40fd-11ea-8497-f708d84323ec.png)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.33.2

Upon further discussion, it has been decided that instead of a red background actual selection (as if the items have been selected with the mouse) will mark the related table elements, as shown in the picture below.

![image](https://user-images.githubusercontent.com/48832842/73367150-620dc100-42af-11ea-8183-6ef7cf412259.png)

**Comment by brita-sed** [comment]
Now the background is blue under selection with "User feedback disabled" elements, and the pop-up windows is there when is should. Corrected. 

![bug_corrected_blue_bg](https://user-images.githubusercontent.com/16755484/73475108-ffd8bd00-438f-11ea-953a-802483737d26.jpg)

![popup_disable_corrected](https://user-images.githubusercontent.com/16755484/73475185-23036c80-4390-11ea-89e5-00fb3db872e1.JPG)
