### ISSUE TITLE
Format of decimal numbers are not the same (dot or comma)

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#49]
**Steps:**
* Start Eclipse. 
* Import simple-junit project. 
* Click on iFL button. 
* Load scores...
* Give filter score manually (a bigger value). 
* Click Apply button. 

**Expected result:**
* The format of the numbers are the same. 

**Actual result:**
* In the error message and on the ruler the numbers are marked with a comma, while for manual entry, only the dot is accepted as a decimal point. It can be deceptive.
![number_format](https://user-images.githubusercontent.com/16755484/60340326-887f1d00-99ab-11e9-8019-c8cfd5a977c2.jpg)

**Version:**
* Eclipse: 2019-06 (4.12.0)
* iFL: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.48.1

**Comment by Dhorvath1294** [comment]
The solution to issue #50 also adresses this problem. Since the plug-in communicates in english, I suggest we use the US locale decimal separator (dot) everywhere to remain consequent and uniform.

![image](https://user-images.githubusercontent.com/48832842/73546581-c6f72180-443d-11ea-85b6-481f172980a8.png)

Screenshot made from version V2.0.50.1 (https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.50.1)

**Comment by brita-sed** [comment]
**Retested** on V2.0.50.1, result: **Corrected**. Now the decimal separator is a dot (.) everywhere. 

![corrected_format](https://user-images.githubusercontent.com/16755484/73867247-a4527780-4846-11ea-8381-9f32bedc8121.jpg)
