### ISSUE TITLE
Activating filtering score: items with zero score will disappear

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#7]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 
1. Click *Load scores...* button. 
1. Load C:\experiment\eclipse\sampleFor_DemoProject.csv. 
1. Select some editable line from the table. 
1. Choose "This is not faulty" option from the right-click menu. 
1. Filter scores moving the slider to the minimum for filtering 0.0000 scores. 

**Expected results**
* Filter score <= 0.0000 won't filter any item, it should show all the lines. 
* Note: maybe it's the right behaviour, in this case the label should be *Filter score < 0.0000*. 

**Received results**
* Activating filtering score -> items with zero score will disappear. 
![zero_filtering](https://user-images.githubusercontent.com/16755484/54041055-0afa8b80-41c7-11e9-882a-3996640111f1.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
This issue reports the expected behavior.

**Comment by abeszedes** [comment]
I don't agree. Expected behavior should be that if the threshold is 0, not filtering is done.

**Comment by brita-sed** [comment]
The expected behavior is thus misleading: if elements with value of 0.000 are should be dropped, then next to "Filter scores" label a "<" relation should be, not ˇ<=". 

![filter_score_from_0](https://user-images.githubusercontent.com/16755484/76637274-bbbe0800-654a-11ea-968c-03beb056b938.jpg)

**Package**: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0

**Comment by geryxyz** [comment]
Maybe the label is not precise. If the score is less or equal than the threshold, then those items will filtered out, ie. removed from the list. Possibly label fix: "hide if score <= [limit]" 

My opinion is that the more strict version (less than rather less or equal than) has reduced the aviable features. Since none of the scores are less than zero, you won't be able to filter them out, while in lequ case you can. Furthermore the lower bound of the filter always be the smallest score of the list, hence with lequ you are able to filter out the least suspicious items currently present, which would be impossible or very hard with less operator.

In the long run we have to and a more sophisticated limit like filter with (maybe multiple) ranges and both upper and lower bounds.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7

I've changed the label to "Show scores" and added the ability to change the relation to either "greater than" (>=) or "less than" (<=) of the filter. I see no reason to add strict inequalities (<, >) or equality (=) for the scores are double values and the newly added options make it possible for the user to see all elements.

![image](https://user-images.githubusercontent.com/48832842/80100001-a12a7600-856f-11ea-9350-435113f49bae.png)

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7. Result: **Corrected**.
